using System.ComponentModel.DataAnnotations;
using WaaS.Common.ViewModel;

namespace WaaS.Space.ViewModel;

public class Account : Credential, ITemporary, IValidatableObject
{
    /// <summary>
    /// An internal ID, set by the backend, when the account has been created successfully.
    /// </summary>
    /// <example>500123456</example>
    public ulong? AccountId { get; set; }

    /// <summary>
    /// The ID to identify the account and operate on.
    /// </summary>
    /// <example>acc-abc12345</example>
    public string? Id { get; set; }

    /// <summary>
    /// An autogenerated username.
    /// </summary>
    /// <example>u12345678</example>
    public string? Username { get; set; }

    /// <summary>
    /// The account password.
    /// </summary>
    /// <example>*****</example>
    [PasswordType(PasswordType.StretchSpace)]
    public override string? Password { get; set; }

    /// <summary>
    /// An external reference for the account, set by the client.
    /// </summary>
    /// <example>my-external-ref-001</example>
    public string? ExtReference { get; set; }

    /// <summary>
    /// Defines protocols which the user can use to login.
    /// </summary>
    /// <example>Sftp, Ssh</example>
    [Required]
    public SpaceAccessType AccessTypes { get; set; } = SpaceAccessType.Sftp | SpaceAccessType.Ssh;

    /// <summary>
    /// List of SSH public keys authorized to log in.
    /// </summary>
    public List<SshPublicKey>? SshPublicKeys { get; set; }

    /// <summary>
    /// Whether SSH public keys from the homedir are also accepted.
    /// </summary>
    /// <example>true</example>
    public bool HomeDirPubKeys { get; set; } = true;

    /// <summary>
    /// Configuration for temporary ressources. One expiration property is allowed only: either ExpireAt or ExpireIn.
    /// </summary>
    public TemporaryInfo? Temporary { get; set; }

    /// <summary>
    /// Locks designed for tenant use cases. Platform admins can set and remove tenant locks as well.
    /// </summary>
    public List<LockInfo>? TenantLocks { get; set; }

    /// <summary>
    /// The type of the account. Can be used to hide certain accounts from customer, e.g. management accounts,
    /// which are used for space setup (Wordpress) and should not be visible for customers.
    /// </summary>
    /// <example>standard</example>
    [Options("standard", "management", "management_ro", AllowNull = true)]
    public string AccountType { get; set; } = "standard";

    public virtual IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        // Only check password and SSH public key correlation on new accounts
        // New accounts do not have an id, username or internalId
        if (Id is null)
        {
            // If the ID is empty, it is a new account.
            // Any other given IDs have to be ignored and reset
            AccountId = null;
            // Username = null; // Do not reset username, as it is alowed to be set on import

            if (Password is null && PasswordToken is null && (SshPublicKeys is null || !SshPublicKeys.Any()))
            {
                yield return new ValidationResult(
                    $"Either a password, password token or SSH keys have to be set",
                    [nameof(Password), nameof(SshPublicKeys)]
                );
            }
        }

        // https://hosting-jira.1and1.org/browse/GPHWAAS-7932
        // TODO: Enable again, when tenants have adjusted
        // if (Expires != null && Expires.Value.ToUniversalTime() > DateTime.UtcNow.AddHours(4))
        //     yield return new ValidationResult(
        //         $"Temporary accounts must not life longer than 4h",
        //         new[] { nameof(Expires) }
        //     );
    }
}