using WaaS.Common.DesiredState;
using WaaS.Space.DesiredState;

namespace WaaS.Space.Classic.DesiredState;

public class SharedWebspace : Space.DesiredState.Space, IWebspace, IPasswordTokenContainer
{
    /// <summary>
    /// Unique id generated by the Webspace Middleware.
    /// </summary>
    public ulong WebspaceId { get; set; }

    public List<Account> Accounts { get; set; } = [];

    /// <summary>
    /// Accounts created and operated using admin-scope.
    /// </summary>
    public List<Account> AdminAccounts { get; set; } = [];

    /// <summary>
    /// A list of customer domains.
    /// We don't manage dns settings for customer domains, the tenant is responsible for it.
    /// </summary>
    public List<DomainBinding<string>> Domains { get; set; } = [];

    /// <summary>
    /// A list of http product subdomains mostly pointing to a webshield ip.
    /// </summary>
    public List<DomainBinding<string>> HttpAccessDomains { get; set; } = [];

    public List<CronTab> CronTabs { get; set; } = [];

    IEnumerable<Account> IWebspace.Accounts => Accounts;

    public override DateTime? CalculateNextCheckTimestamp()
        => Accounts
            .Select(x => x.CalculateNextCheckTimestamp())
            .Concat(AdminAccounts.Select(x => x.CalculateNextCheckTimestamp()))
            .Append(base.CalculateNextCheckTimestamp())
            .Where(x => x.HasValue)
            .Min();

    public IEnumerable<string> GetPasswordTokens()
    {
        var credentials = Enumerable.Empty<ICredential>()
            .Concat(Accounts)
            .Concat(AdminAccounts);

        if (MailConfiguration is not null)
            credentials = credentials.Append(MailConfiguration);

        if (WebAnalytics is not null)
            credentials = credentials.Append(WebAnalytics);

        return credentials
            .Where(x => !string.IsNullOrEmpty(x.SecurePasswordToken))
            .Select(x => x.SecurePasswordToken!);
    }
}