using WaaS.Common.DesiredState;
using WaaS.Persistence;

namespace WaaS.Space.DesiredState;

public class DomainBinding<TEnvironment> : WaasResource, IDomainBinding
{
    /// <summary>
    /// Unique id generated by the Webspace Middleware.
    /// </summary>
    public ulong? DomainId { get; set; }

    [LookupKey(LookupResourceKeyType.DomainName)]
    public string DomainName { get; set; } = "";

    /// <summary>
    /// State of the domain binding, reported by the Webspace Middleware.
    /// </summary>
    public string State { get; set; } = "unknown";

    /// <summary>
    /// By False the domain is not activated on Webspace Middleware,
    /// so it is not provisioned on the web server.
    /// </summary>
    public bool? IsEnabled { get; set; }

    public TargetDirectory TargetPath { get; set; } = new();

    public DomainConnectType ConnectType { get; set; }

    /// <summary>
    /// PHP version mostly.
    /// </summary>
    public TEnvironment Environment { get; set; } = default!;

    /// <summary>
    /// GPHWAAS-7264: a list of locks
    /// </summary>
    public List<LockItem> LockItems { get; set; } = [];

    public override string ToString() => DomainName;
}