<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
  </ItemGroup>

  <ItemGroup>
    <ProtoFiles Include="Proto\*.proto" />
  </ItemGroup>

  <Target Name="GenerateProtobuf" BeforeTargets="BeforeBuild"
          Inputs="@(ProtoFiles)" 
          Outputs="@(ProtoFiles->'Generated/%(Filename).cs')"
          Condition="'$(SkipProtogen)' != 'true'">
          
    <MakeDir Directories="Generated" />
    <Exec Command="dotnet tool restore" />
    <Exec Command="dotnet protogen --csharp_out=Generated -IProto +names=original +nullablevaluetype=yes +repeatedaslist=yes --package=WaaS.Webshield.ProtoBuf @(ProtoFiles->'%(Filename)%(Extension)', ' ')" />
  </Target>
</Project>
