<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WaaS.Space.Classic.Workflow\WaaS.Space.Classic.Workflow.csproj" />
    <ProjectReference Include="..\..\WaaS.Space.Workflow\WaaS.Space.Workflow.csproj" />
    <ProjectReference Include="..\..\..\Webshield\WaaS.Webshield.DesiredState\WaaS.Webshield.DesiredState.csproj" />
  </ItemGroup>

</Project>
