using WaaS.Space.ViewModel;

namespace WaaS.SharedWebspaceManager.ViewModel;

/// <summary>
/// Space related data.
/// </summary>
public class SharedWebspaceData : WebspaceData
{
    /// <summary>
    /// Space ID generated by the backendp.
    /// </summary>
    /// <example>1234567</example>
    public ulong? WebspaceId { get; set; }
}

