<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Common\WaaS.Common.Changes\WaaS.Common.Changes.csproj" />
    <ProjectReference Include="..\..\src\Systems\Space\WaaS.Space.DesiredState\WaaS.Space.DesiredState.csproj" />
  </ItemGroup>

</Project>
