using System.Text.RegularExpressions;

namespace WaaS.Persistence;

public interface IHashValidation
{
    string SystemType { get; set; }
    bool IsValidHash(string hash);
}

public partial class CryptHashOptions : IHashValidation
{
    public const int DefaultRounds = 32768; // 2^15

    [GeneratedRegex(@"^\$(?<scheme>[0-9a-z])\$rounds=(?<rounds>\d+)\$[a-zA-Z0-9./]+\$[a-zA-Z0-9./]+$")]
    private static partial Regex CryptHashRegEx();

    public required string SystemType { get; set; }

    public string SchemeId { get; set; } = "5";

    // As a base value, be use our default rounds value used by the password store.
    // See https://git.ionos.org/WCLI/waas-crypt/src/branch/master/WaaS.Crypt/BusinessLogic/HashGenerator.cs
    // 2^15 = 32768
    public int MinRounds { get; set; } = (int)Math.Round(DefaultRounds * 0.5);
    public int MaxRounds { get; set; } = DefaultRounds * 2;

    public bool IsValidHash(string hash)
    {
        var matches = CryptHashRegEx().Matches(hash);

        if (matches.Count == 0)
            return false;

        var match = matches[0];

        if (match.Groups["scheme"].Value != SchemeId)
            return false;
            
        var rounds = int.Parse(match.Groups["rounds"].Value);

        if (rounds < MinRounds)
            return false;

        if (rounds > MaxRounds)
            return false;

        return true;
    }
}

public class ImportProfile
{
    public string[] UsernamePatterns { get; set; } = [@"^u\d+$"];
    public CryptHashOptions[] AllowedCryptHashes { get; set; } = [];
}

/// <summary>
/// Model for the tenant profile with attached default values.
/// Be careful by changing the default values. It can have a big impact on our tenants.
/// </summary>
public class TenantProfile
{
    /// <summary>
    /// It can be a company name, a team name or something else.
    /// A partner can have several tenants.
    /// Example:
    /// - Partner Name = UDAG
    ///   - Tenant Name 1: base_udag
    ///   - Tenant Name 2: sandbox_udag
    /// </summary>
    public string? PartnerName { get; set; } = string.Empty;

    /// <summary>
    /// Flag whether the given tenant is a test tenant.
    /// In some use cases there is a difference in behavior between live and test tenants.
    /// </summary>
    public bool? TestTenant { get; set; } = true;

    /// <summary>
    /// DEPRECATED, see DataAccessDomainFormats.
    /// </summary>
    public string? DataAccessDomainFormat { get; set; } = "access-{SYSTEM-INSTANCE-ID}.webspace-host.com";

    /// <summary>
    /// Formats of product subdomains for data access.
    /// </summary>
    public List<string>? DataAccessDomainFormats { get; set; } = ["access-{SYSTEM-INSTANCE-ID}.webspace-host.com"];

    /// <summary>
    /// DEPRECATED, see HttpAccessDomainFormats.
    /// </summary>
    public string? HttpAccessDomainFormat { get; set; } = "home-{SYSTEM-INSTANCE-ID}.webspace-host.com";

    /// <summary>
    /// Formats of product subdomains for http access.
    /// </summary>
    public List<string>? HttpAccessDomainFormats { get; set; } = ["home-{SYSTEM-INSTANCE-ID}.webspace-host.com"];

    /// <summary>
    /// DEPRECATED, see DatabaseAccessDomainFormats.
    /// </summary>
    public string? DatabaseAccessDomainFormat { get; set; } = "database-{SYSTEM-INSTANCE-ID}.webspace-host.com";

    /// <summary>
    /// Formats of product subdomains for database access.
    /// </summary>
    public List<string>? DatabaseAccessDomainFormats { get; set; } = ["database-{SYSTEM-INSTANCE-ID}.webspace-host.com"];

    /// <summary>
    /// Default lifetime of temporary accounts in seconds.
    /// </summary>
    public long? TemporaryAccountLifetimeDefault { get; set; } = 14400;

    /// <summary>
    /// Default lifetime of temporary webspaces in seconds.
    /// </summary>
    public long? TemporaryWebspaceLifetimeDefault { get; set; } = 604800;

    /// <summary>
    /// If true, no notifications are generated by temporary errors.
    /// </summary>
    public bool? SuppressTempErrorNotifications { get; set; } = true;

    /// <summary>
    /// If true, no notifications are generated by the cleanup process.
    /// </summary>
    public bool? SuppressCleanupNotifications { get; set; } = true;

    /// <summary>
    /// If true, the tenant is able to set tags on the Stack Instance level.
    /// </summary>
    public bool? StackInstanceTagsAllowed { get; set; } = false;

    /// <summary>
    /// If true (default), the tenant is able to enable or disable Biofilter.
    /// </summary>
    public bool? BiofilterConfigurationAllowed { get; set; } = false;

    /// <summary>
    /// If true, the tenant is able to use compat links, when creating webspaces.
    /// </summary>
    public bool? CompatLinksAllowed { get; set; } = false;

    /// <summary>
    /// If true, the tenant is able to manage cdn mappings.
    /// </summary>
    public bool? CdnMappingsAllowed { get; set; } = false;

    /// <summary>
    /// If true, the tenant is able to change region within the same Stack Instance zone.
    /// </summary>
    public bool? DatabaseRegionAllowed { get; set; } = false;

    /// <summary>
    /// If true, the tenant is able to change region within the same Stack Instance zone.
    /// </summary>
    public bool? WebspaceRegionAllowed { get; set; } = false;

    /// <summary>
    /// Object for limits.
    /// </summary>
    public LimitsInfo? Limits { get; set; } = new LimitsInfo();

    /// <summary>
    /// Object for default values.
    /// </summary>
    public DefaultsInfo? Defaults { get; set; } = new DefaultsInfo();

    public class LimitsInfo
    {
        /// <summary>
        /// Max resource level per webspace. Currently the following values are supported: XS, S, M, L, XL and XXL.
        /// </summary>
        public string? ResourceLevel { get; set; } = "M";

        /// <summary>
        /// Max resource level per database. Currently the following values are supported: S and M.
        /// </summary>
        public string? DatabaseResourceLevel { get; set; } = "S";

        /// <summary>
        /// Max disk quota per webspace in bytes.
        /// </summary>
        public ulong? DiskQuotaInBytes { get; set; } = 2199023255552; // 2 TB

        /// <summary>
        /// Max database quota in bytes.
        /// </summary>
        public ulong? DatabaseQuotaInBytes { get; set; } = 1000000000;

        /// <summary>
        /// Max count of webspaces per Stack Instance.
        /// </summary>
        public int? WebspacesPerStack { get; set; } = 5000;

        /// <summary>
        /// Max count of stretchspaces per Stack Instance.
        /// </summary>
        public int? StretchSpacesPerStack { get; set; } = 5000;

        /// <summary>
        /// Max count of databases per Stack Instance.
        /// </summary>
        public int? DatabasesPerStack { get; set; } = 5000;

        /// <summary>
        /// Max count of domains per single webspace.
        /// </summary>
        public int? DomainsPerWebspace { get; set; } = 5000;

        /// <summary>
        /// Max count of accounts per single webspace.
        /// </summary>
        public int? AccountsPerWebspace { get; set; } = 200;

        /// <summary>
        /// Max count of accounts per single database.
        /// </summary>
        public int? AccountsPerDatabase { get; set; } = 200;

        /// <summary>
        /// Count of seconds after which the webspace/database is automatically removed. It should be set by sandbox tenants.
        /// </summary>
        public ulong? LifetimeInSeconds { get; set; } = null;

        /// <summary>
        /// Max count of cron jobs per single webspace.
        /// </summary>
        public int? CronJobsPerWebspace { get; set; } = 100;

        /// <summary>
        /// The maximum ratelimit for the WAF, which the tenant can set.
        /// </summary>
        public uint? MaxWafRatelimit { get; set; } = 100;
    }

    public class DefaultsInfo
    {
        /// <summary>
        /// Default resource level per webspace. Currently the following values are supported: XS, S, M, L, XL and XXL.
        /// </summary>
        public string? ResourceLevel { get; set; } = "XS";

        /// <summary>
        /// Default resource level per database. Currently the following values are supported: S and M.
        /// </summary>
        public string? DatabaseResourceLevel { get; set; } = "S";

        /// <summary>
        /// Default database type.
        /// </summary>
        public string? DatabaseType { get; set; } = "mariadb";

        /// <summary>
        /// Default database version.
        /// </summary>
        public string? DatabaseVersion { get; set; } = "10.11";

        /// <summary>
        /// Default disk quota per webspace in bytes.
        /// </summary>
        public ulong? DiskQuotaInBytes { get; set; } = 50000000;

        /// <summary>
        /// Default database quota in bytes.
        /// </summary>
        public ulong? DatabaseQuotaInBytes { get; set; } = 1000000000;

        /// <summary>
        /// Default proxy mapping mode. From Planner: Proxy = 1, ProxyForceSsl = 2.
        /// </summary>
        public int? ProxyMappingMode { get; set; } = 1;
    }

    public List<QuotaProfile>? QuotaProfiles { get; set; } = null;

    public class QuotaProfile
    {
        /// <summary>
        /// Quota profile name.
        /// </summary>
        public string? Name { get; set; } = string.Empty;

        /// <summary>
        /// It is for future use. Currently there is only one algorithm for quota increase / decrease.
        /// </summary>
        public string? AlgorithmType { get; set; } = "default";

        /// <summary>
        /// It is a value in percent after which the quota is increased automatically.
        /// Value MUST be between 50% and 100%
        /// (Limit 1000mb with 90% = quota increase when more than 900mb are used.)
        /// </summary>
        public int? AutoQuotaIncreaseThreshold { get; set; } = 75;

        /// <summary>
        /// It is a value in percent after which the quota is decreased automatically.
        /// Value MUST be between 0% and 50%
        /// (Limit 1000mb with 10% = quota decrese when less than 100mb are used.)
        /// </summary>
        public int? AutoQuotaDecreaseThreshold { get; set; } = 50;

        /// <summary>
        /// It is the portion of the quota added or substracted by a quota change.
        /// If the value exceeds the opposite boundary it should be capped in implementation.
        /// (The value should be larger than 1mb. For production maybe even larger than 10mb.)
        /// </summary>
        public ulong? AutoQuotaStepSizeInBytes { get; set; } = 10737418240;

        /// <summary>
        /// It is a time period in seconds until the next possible automatic quota change.
        /// (For production the value should be larger than an hour to prevent too many cycles.)
        /// </summary>
        public ulong? AutoQuotaLockPeriod { get; set; } = 28800;
    }

    /// <summary>
    /// A list of domain environments for classic webspaces.
    /// </summary>
    public List<string>? SupportedEnvironments { get; set; } = ["php4", "php5.2", "php5.4", "php5.5", "php5.6", "php7", "php7.1", "php7.2", "php7.3", "php7.4", "php8", "php8.1", "php8.2", "php8.3", "php8.4"];

    /// <summary>
    /// DEPRECATED, will be removed soon.
    /// </summary>
    public List<string>? SupportedStretchSpaceEnvironments { get; set; } = null;

    /// <summary>
    /// A list of domain environments for stretchspaces.
    /// </summary>
    public List<string>? StretchSpaceDomainEnvironments { get; set; } = ["noscript", "php8.1", "apache-php8.1", "wp-apache-php8.0", "wp-apache-php8.1", "wp-apache-php8.2", "wp-apache-php8.3", "nginx-php8.0", "nginx-php8.1", "nginx-php8.2", "nginx-php8.3", "_dev_strato1"];

    /// <summary>
    /// A list of account environments for stretchspaces.
    /// </summary>
    public List<string>? StretchSpaceAccountEnvironments { get; set; } = ["php8.1", "apache-php8.1", "wp-apache-php8.0", "wp-apache-php8.1", "wp-apache-php8.2", "wp-apache-php8.3", "nginx-php8.0", "nginx-php8.1", "nginx-php8.2", "nginx-php8.3", "_dev_strato1"];

    /// <summary>
    /// A list of crontab environments for stretchspaces.
    /// </summary>
    public List<string>? StretchSpaceCrontabEnvironments { get; set; } = ["php8.1", "apache-php8.1", "wp-apache-php8.0", "wp-apache-php8.1", "wp-apache-php8.2", "wp-apache-php8.3", "nginx-php8.0", "nginx-php8.1", "nginx-php8.2", "nginx-php8.3", "_dev_strato1"];

    /// <summary>
    /// DEPRECATED. see DatabaseTransitions.
    /// </summary>
    public List<string>? SupportedDatabaseTypes { get; set; } = ["mysql", "mariadb"];

    /// <summary>
    /// DEPRECATED. see DatabaseTransitions.
    /// </summary>
    public List<string>? SupportedDatabaseVersions { get; set; } = ["5.7", "8.0", "10.5", "10.6", "10.11"];

    public List<string>? SupportedResourceLevels { get; set; } = ["XS", "S", "M", "L", "XL", "XXL"];

    public List<string>? SupportedDatabaseResourceLevels { get; set; } = ["S", "M"];

    public List<string>? SupportedWebspacePlacementTags { get; set; } = ["webspace:default"];

    public List<string>? SupportedStretchSpacePlacementTags { get; set; } = ["stretchspace:default"];

    public List<string>? SupportedDatabasePlacementTags { get; set; } = ["database:default"];

    public List<string>? SupportedMsSqlDbPlacementTags { get; set; } = ["mssqldb:default"];

    public List<string>? SupportedWebspaceRegions { get; set; } = ["europe", "europe-uk1", "america"];

    public List<string>? SupportedDatabaseRegions { get; set; } = ["europe", "europe-uk1", "america"];

    public List<string>? SupportedProductDnsHostnames { get; set; } = null;

    public InfrastructureCertificateOperations? SupportedCertificateOperations { get; set; } = null;

    public ImportProfile? WebspaceImport { get; set; } = null;

    /// <summary>
    /// Allowed CRUD operations for product sub-domains certificates
    /// </summary>
    public class InfrastructureCertificateOperations
    {
        public bool? DeleteCertificateAllowed { get; set; } = false;
        public bool? AddCertificateAllowed { get; set; } = false;
    }

    public List<DatabaseTransition>? DatabaseTransitions { get; set; } =
    [
        new DatabaseTransition { Destination = new DatabaseInfo { DatabaseType = "mysql", DatabaseVersion = "5.7" } },
        new DatabaseTransition { Destination = new DatabaseInfo { DatabaseType = "mysql", DatabaseVersion = "8.0" } },
        new DatabaseTransition { Destination = new DatabaseInfo { DatabaseType = "mariadb", DatabaseVersion = "10.5" } },
        new DatabaseTransition { Destination = new DatabaseInfo { DatabaseType = "mariadb", DatabaseVersion = "10.6" } },
        new DatabaseTransition { Destination = new DatabaseInfo { DatabaseType = "mariadb", DatabaseVersion = "10.11" } },
    ];

    public class DatabaseTransition
    {
        public DatabaseInfo? Source { get; set; } = null;
        public DatabaseInfo? Destination { get; set; }
    }

    public class DatabaseInfo
    {
        public string? DatabaseType { get; set; }
        public string? DatabaseVersion { get; set; }
    }
}
