<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Temporalio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WaaS.Space.Classic.DesiredState\WaaS.Space.Classic.DesiredState.csproj" />
    <ProjectReference Include="..\WaaS.Space.Classic.ViewModel\WaaS.Space.Classic.ViewModel.csproj" />
    <ProjectReference Include="..\..\WaaS.Space.Workflow\WaaS.Space.Workflow.csproj" />
    <ProjectReference Include="..\..\..\Webshield\WaaS.Webshield.Workflow\WaaS.Webshield.Workflow.csproj" />
    <ProjectReference Include="..\..\..\..\Common\WaaS.Common.Workflow\WaaS.Common.Workflow.csproj" />
  </ItemGroup>

</Project>
