using WaaS.Space.ViewModel;

namespace WaaS.Space.Classic.ViewModel;

/// <summary>
/// Space related data.
/// </summary>
public class StretchspaceData : SpaceData
{
    /// <summary>
    /// Space ID generated by the backend.
    /// </summary>
    /// <example>1234567</example>
    public ulong? StretchspaceId { get; set; }
}

